import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from datetime import datetime

def generate_medical_report(patient_name, age, gender, detection_result, confidence, original_img_path, output_pdf_path):
    doc = SimpleDocTemplate(output_pdf_path, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    header_style = ParagraphStyle(
        name='Header',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#0055A4'), # Hospital Blue
        alignment=1, # Center
        spaceAfter=5
    )
    
    subheader_style = ParagraphStyle(
        name='SubHeader',
        fontSize=10,
        textColor=colors.dimgrey,
        alignment=1,
        spaceAfter=25
    )
    
    section_title = ParagraphStyle(
        name='SectionTitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#0055A4'),
        spaceBefore=15,
        spaceAfter=10
    )
    
    body_style = ParagraphStyle(
        name='Body',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=8,
        leading=16
    )

    story = []
    
    # Header
    story.append(Paragraph("NeuroDiagnostics Advanced AI Lab", header_style))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Attending Physician: Dr. E. Carter (Neurology)", subheader_style))
    story.append(Spacer(1, 10))
    
    # Patient Details Table
    patient_data = [
        ['Patient Name:', patient_name, 'Patient ID:', f"PT-84729"],
        ['Age:', str(age), 'Gender:', gender]
    ]
    t_patient = Table(patient_data, colWidths=[100, 150, 100, 150])
    t_patient.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,1), 'Helvetica'),
        ('FONTNAME', (3,0), (3,1), 'Helvetica'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LINEBELOW', (0,1), (-1,1), 1, colors.HexColor('#E2E8F0')),
    ]))
    story.append(t_patient)
    story.append(Spacer(1, 25))
    
    # Diagnosis Section
    story.append(Paragraph("AI Diagnostic Analysis", section_title))
    
    dist_color = colors.HexColor('#DC2626') if 'Tumor Detected' in detection_result else colors.HexColor('#16A34A')
    
    diag_data = [
        ['Detection Result:', detection_result],
        ['AI Confidence Score:', f"{confidence * 100:.2f}%"]
    ]
    t_diag = Table(diag_data, colWidths=[150, 250])
    t_diag.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,1), 'Helvetica'),
        ('TEXTCOLOR', (1,0), (1,0), dist_color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_diag)
    story.append(Spacer(1, 25))
    
    # Scan Visual
    story.append(Paragraph("Uploaded Scan Image", section_title))
    if os.path.exists(original_img_path):
        from PIL import Image
        with Image.open(original_img_path) as img:
            ratio = img.width / img.height
            h = 250
            w = h * ratio
            if w > 400:
                w = 400
                h = w / ratio
            rl_img = RLImage(original_img_path, width=w, height=h)
            story.append(rl_img)
    else:
        story.append(Paragraph("Image not available for print format.", body_style))
    story.append(Spacer(1, 25))
    
    # Recommendations
    story.append(Paragraph("Clinical Recommendations", section_title))
    if 'Tumor Detected' in detection_result:
        rec = "<ul><li>Schedule immediate consultation with a Neurologist or Neurosurgeon.</li><li>Conduct follow-up MRI with Gadolinium contrast to confirm tumor dimensions.</li><li>Patient should be monitored for neurological symptoms (headaches, seizures, cognitive changes).</li></ul>"
    else:
        rec = "<ul><li>No immediate signs of tumor mass detected in this scan.</li><li>Routine neurological health monitoring recommended as per standard preventative care.</li><li>Maintain a healthy lifestyle emphasizing cardiovascular exercise and anti-inflammatory diet.</li></ul>"
    
    story.append(Paragraph(rec, body_style))
    story.append(Spacer(1, 40))
    
    # Footer
    footer_text = "Disclaimer: This report is generated by a Hybrid Deep Learning (ViT+CNN) AI System. It is an experimental tool and NOT a substitute for professional medical diagnosis. Please consult a licensed physician."
    footer_style = ParagraphStyle(name='Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray, alignment=1)
    story.append(Paragraph(footer_text, footer_style))
    
    # Build PDF
    doc.build(story)
